### ISSUE TITLE
Loggers should be customizable

### ISSUE THREAD

**Issue by bfink13** [indeedeng/rabbitmq-operator#46]
Our default log level is INFO. In #40 we added API logging but those are at the DEBUG level. Unfortunately the only way to see DEBUG logs is to build from source and deploy. We should let end users customize log levels for the various loggers via the operator yaml.

We might be able to mimic what Strimzi Kafka did: https://strimzi.io/docs/latest/#assembly-logging-deployment-configuration-kafka

**Comment by jhamacher-indeed** [comment]
@bfink13 this ticket concerns the logging level of the operator itself, correct?

**Comment by bfink13** [comment]
Yep.

**Comment by jhamacher-indeed** [comment]
Skimming the strimzi link, I think a reasonable first approach would be to configure this via a ConfigMap.  If the map isn't present we do what we already do, if it is present we do what it says.  I think we can just require it to be named something specific rather than supporting different names.  Seem reasonable, or would you like to see something more flexible?

**Comment by bfink13** [comment]
That seems like a fine approach to me. We can always add on later.

**Comment by jhamacher-indeed** [comment]
This is turning out to be more complex than I anticipated, for several reasons.
1. I think the Strimzi example allows you to configure the logging level of the Kafka instances themselves by embedding logging configuration into the CRD.  This would allow their operator to build the appropriate log4j configuration prior to starting the instance.
2. In our case we want to change the logging level of the operator itself.  This means that we either need to restart the operator every time we change the configuration, or enable some sort of dynamic reconfiguration.
3. Log4j2 supports dynamically reloading configuration (via the monitorInterval parameter on the top-level Configuration) and it supports loading configuration from multiple configuration files.  This all sounded very promising.
4. However, I've been running into a very large roadblock called "spring boot".  Specifically, it imposes its own idea about logging configuration - it provides a single file to log4j2.
5. You can still use xincludes within the xml configuration file, so that's probably the path of least resistance.  However, this means we'll need to embed XML in the ConfigMap.  Blech.

The only other semi-reasonable alternative seems to be to programmatically alter the logging configuration, but that seems even messier than the XML route.

I'd love to hear some alternatives if I missed something.

**Comment by jhamacher-indeed** [comment]
I never was able to figure out the dynamic loading.  A more careful reading of the documentation revealed that this only works for file-based configuration; we provide the base configuration file via the classpath.  I verified experimentally that changes to a file included from that file are not monitored.

**Comment by jhamacher-indeed** [comment]
https://github.com/indeedeng/rabbitmq-operator/pull/52
